version: '2'

services:
  invoiceninja:
    image: moss/invoiceninja:${version}
{{- if (.Values.public_port)}}
    ports:
      - ${public_port}:????
{{- end}}
{{- if not (.Values.mysql_host)}}
    links:
      - mysql:db
{{- end }}
    environment:
      APP_DEBUG: false
      APP_URL: ${base_url}
      DB_TYPE: mysql
      DB_DATABASE: ${mysql_database}
      DB_PASSWORD: ${mysql_password}
      DB_USERNAME: ${mysql_user}
{{- if (.Values.mysql_host)}}
      DB_HOST: ${mysql_host}
{{- end}}
      APP_ENV: production
      TRUSTED_PROXIES: 0.0.0.0/0

{{- if not (.Values.mysql_host)}}
  mysql:
    image: mariadb:10.3.7
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--mysql-data:/var/lib/mysql
    labels:
      io.rancher.container.hostname_override: container_name
{{- end}}
