version: '2'

.catalog:
  name: "prometheus"
  version: "0.0.1"
  description: "Prometheus Monitoring Solution"
  uuid: prometheus
  minimum_rancher_version: v1.5.5
  questions:
    - variable: "RANCHER_SERVER"
      label: "Rancher Server"
      description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
      default: "0.0.0.0"
      required: false
      type: "string"
    - variable: external_driver
      label: 'External Driver'
      type: string
      default: rancher-nfs
    - variable: enable_ports
      label: 'Enable Ports'
      type: enum
      required: true
      default: false
      options:
        - true
        - false
    - variable: enable_ports
      label: 'Allow Signup'
      type: enum
      required: true
      default: false
      options:
        - true
        - false

services:
  prometheus:
    scale: 1
    health_check:
      port: 9090
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

  grafana:
    scale: 1
    health_check:
      port: 3000
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

  prometheus-rancher-exporter:
    scale: 1
    health_check:
      port: 9173
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000
