version: '2'

services:
  tao:
    image: jamrizzi/tao:stable
    links:
      - mariadb:database
{{- if eq .Values.enable_ports "true"}}
    ports:
      - 8080:8080
{{- end}}

  mariadb:
    image: mariadb:10.2.12
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: tao
      MYSQL_PASSWORD: ${database_password}
      MYSQL_DATABASE: tao
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--tao-data:/var/lib/mysql
