version: '2'

catalog:
  name: tao
  version: 0.0.1
  description: 'Open source assessment platform'
  uuid: prometheus
  minimum_rancher_version: v1.5.5
  questions:
    - variable: database_password
      label: 'Database Password'
      default: hellodocker
      required: false
      type: password
    - variable: volume_driver
      label: 'Volume Driver'
      required: true
      default: rancher-nfs
      type: enum
      options:
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
        - local
    - variable: enable_ports
      label: 'Enable Ports'
      type: enum
      required: true
      default: false
      options:
        - true
        - false
    - variable: manuel_setup
      label: 'Manuel Setup'
      type: enum
      required: true
      default: false
      options:
        - true
        - false
    - variable: operated_by_name
      label: 'Operated By Name'
      default: 'JamRizzi Technologies'
      required: false
      type: string
    - variable: operated_by_email
      label: 'Operated By Email'
      default: email@example.com
      required: false
      type: string
    - variable: root_url
      label: 'Root Url'
      default: http://localhost
      required: false
      type: string
    - variable: user_firstname
      label: 'User Firstname'
      required: true
      type: string
    - variable: user_lastname
      label: 'User Lastname'
      required: true
      type: string
    - variable: user_email
      label: 'User Email'
      required: true
      type: string
    - variable: user_password
      label: 'User Password'
      required: true
      type: password
    - variable: timezone
      label: Timezone
      default: UTC
      required: false
      type: string

services:
  tao:
    scale: 1
    health_check:
      port: 80
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

  mariadb:
    scale: 1
    health_check:
      port: 3306
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000
