version: '2'

services:
  postgres:
    image: postgres:10.2-alpine
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${database_password}
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--tao-database:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.7.3
    hostname: rabbit

  redis:
    image: redis:3.2.11

  celery:
    image: celery:4.0.2
    links:
      - rabbit

  events:
    image: kartoffeltoby/taiga-events:latest
    links:
      - rabbit

  taiga:
    image: kartoffeltoby/taiga:latest
    restart: always
{{- if eq .Values.enable_ports "true"}}
    ports:
      - 80:80
{{- end}}
    links:
      - postgres
      - events
      - rabbit
      - redis
    environment:
      - TAIGA_HOSTNAME=${hostname}
      - TAIGA_DB_HOST=postgres
      - TAIGA_DB_NAME=taiga
      - TAIGA_DB_USER=taiga
      - TAIGA_DB_PASSWORD=${database_password}
      - HTTPS_SELF_DOMAIN=${hostname}
      - TAIGA_SSL=True
      - TAIGA_SLEEP=10
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--tao-files:/usr/src/taiga-back/media
