version: '2'

services:
  postgres:
    image: postgres:10.2-alpine
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${database_password}
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--taiga-database:/var/lib/postgresql/data
