version: '2'
catalog:
  name: "SonarQube"
  version: "v6.7"
  description: "SonarQube"
  uuid: sonarqube-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: docker_version
      description: "SonarQube docker version"
      label: "SonarQube docker version"
      required: true
      default: "6.7-alpine"
      type: "enum"
      options:
        - 6.7-alpine
        - 6.7
    - variable: jvm_opts
      description: "SonarQube web jvm options"
      label: "SonarQube web jvm options"
      required: false
      default: ""
      type: "string"
    - variable: postgres_port
      description: "Postgres Port"
      label: "Postgres Port"
      required: true
      default: "5432"
      type: "int"
    - variable: postgres_db
      description: "Postgres Database Name"
      label: "Postgres Database"
      required: true
      default: "sonar"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "sonar"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "sonar"
      type: "password"
    - variable: volume_driver
      label: 'Volume Driver'
      required: true
      default: rancher-nfs
      type: enum
      options:
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
        - local
    - variable: enable_ports
      label: 'Enable Ports'
      type: enum
      required: true
      default: false
      options:
        - true
        - false

services:
  sonarqube:
    scale: 1
    retain_ip: true
    health_check:
      port: 9000
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
