cadvisor:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: google/cadvisor:latest
  stdin_open: true
  volumes:
    - '/:/rootfs:ro'
    - '/var/run:/var/run:rw'
    - '/sys:/sys:ro'
    - '/var/lib/docker/:/var/lib/docker:ro'

node-exporter:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: prom/node-exporter:latest
  stdin_open: true

prom-conf:
  tty: true
  image: infinityworks/prom-conf:20
  volumes:
    - /etc/prom-conf/
  net: none

prometheus:
  tty: true
  image: prom/prometheus:v2.1.0
  command: --config.file=/etc/prom-conf/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles
{{- if eq .Values.enable_ports "true"}}
  ports:
    - 9090:9090
{{- end}}
  labels:
    io.rancher.sidekicks: prom-conf
  volumes_from:
    - prom-conf
  volume_driver: ${volume_driver}
  volumes:
    - {{.Stack.Name}}--prometheus-data:/prometheus
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - prometheus-rancher-exporter:prometheus-rancher-exporter
  extra_hosts:
    - rancher-server:${rancher_server}

graf-db:
  tty: true
  image: infinityworks/graf-db:11
  command: cat
  volume_driver: ${volume_driver}
  volumes:
    - {{.Stack.Name}}--graf-db-data:/var/lib/grafana
  net: none

grafana:
  tty: true
  image: grafana/grafana:5.0.0
  environment:
    - GF_USERS_ALLOW_SIGN_UP=false
{{- if eq .Values.enable_ports "true"}}
  ports:
    - 3000:3000
{{- end}}
  labels:
    io.rancher.sidekicks: graf-db
  volumes_from:
    - graf-db
  links:
    - prometheus:prometheus
    - prometheus-rancher-exporter:prometheus-rancher-exporter

prometheus-rancher-exporter:
  tty: true
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
  image: infinityworks/prometheus-rancher-exporter:v0.22.52
