version: '2'

catalog:
  name: Grafana
  version: '0.1.0'
  description: |
    Data visualization and monitoring with prometheus integration
  minimum_rancher_version: v1.5.5
  questions:
    - variable: rancher_server_ip
      label: 'Rancher Server IP'
      default: '0.0.0.0'
      required: false
      type: string
    - variable: open_registration
      label: 'Open Registration'
      type: enum
      default: false
      options:
        - true
        - false
    - variable: prometheus_version
      label: 'Prometheus Version'
      type: enum
      default: v2.1.0
      options:
        - v2.1.0
        - latest
    - variable: grafana_version
      label: 'Grafana Version'
      type: enum
      default: 5.0.0
      options:
        - 5.0.0
        - latest
    - variable: volume_driver
      label: 'Volume Driver'
      required: true
      default: rancher-nfs
      type: enum
      options:
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
        - local
    - variable: prometheus_public_port
      label: 'Prometheus Public Port'
      description: 'Leave empty if you do not want an exposed port'
      type: string
      required: false
    - variable: grafana_public_port
      label: 'Grafana Public Port'
      description: 'Leave empty if you do not want an exposed port'
      type: string
      required: false

services:
  prometheus:
    scale: 1
    health_check:
      drain_timeout_ms: 10000
      healthy_threshold: 2
      interval: 2000
      port: 9090
      request_line: GET / HTTP/1.0
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3

  grafana:
    scale: 1
    health_check:
      drain_timeout_ms: 10000
      healthy_threshold: 2
      interval: 2000
      port: 3000
      request_line: GET / HTTP/1.0
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3

  prometheus-rancher-exporter:
    scale: 1
    health_check:
      drain_timeout_ms: 10000
      healthy_threshold: 2
      interval: 2000
      port: 9173
      request_line: GET / HTTP/1.0
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3
