blogdown:
  image: thingdown/blogdown:latest
  tty: true
  labels:
    io.rancher.container.pull_image: always

deputy:
  image: thingdown/deputy:latest
  environment:
    GIT_REPO: ${git_repo}
    GIT_BRANCH: ${git_branch}
    GIT_USERNAME: ${git_username}
    GIT_PASSWORD: ${git_password}
  tty: true
  volumes:
    - blogdown-data:/app/content
  labels:
    io.rancher.container.pull_image: always
