blogdown:
  image: thingdown/blogdown:latest
  ports:
    - 5000:5000
  tty: true
  labels:
    io.rancher.container.pull_image: always

deputy:
  image: thingdown/deputy:latest
  ports:
    - 3000:3000
  environment:
    GIT_REPO: ${git_repo}
    GIT_BRANCH: ${git_branch}
    GIT_USERNAME: ${git_username}
    GIT_PASSWORD: ${git_password}
    CONTENT_PATH: /app/content
  tty: true
  volumes:
    - blogdown-data:/app/content
  labels:
    io.rancher.container.pull_image: always
