drone-server:
    image: drone/drone:0.5
    environment:
        DRONE_OPEN: 'true'
        DRONE_GITHUB: 'true'
        DRONE_GITHUB_CLIENT: ${drone_github_client}
        DRONE_GITHUB_SECRET: ${drone_github_secret}
        DRONE_SECRET: ${drone_secret}
        DRONE_ORGS : ${drone_orgs}
        DRONE_DATABASE_DRIVER: mysql
        DRONE_DATABASE_DATASOURCE: root:${mysql_root_password}@tcp(db:3306)/${mysql_database}?parseTime=true
    links:
        - drone-data:db

drone-agent:
    image: drone/drone:0.5
    environment:
        DRONE_SERVER: ws://drone-server:8000/ws/broker
        DRONE_SECRET: ${drone_secret}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - drone-server:drone-server
    command:
        - agent

drone-data:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: ${mysql_root_password}
        MYSQL_DATABASE: ${mysql_database}
        stdin_open: true
    volumes:
        - ${drone_data}:/var/lib/mysql
    labels:
        ident: 'true'
