version: '2'

catalog:
  name: Drone
  version: 0.1.0
  description: |
    A continuous delivery system built on container technology
  questions:
    - variable: base_url
      label: 'Base URL'
      required: true
      type: string
    - variable: agent_scale
      label: 'Agent Scale'
      required: true
      default: 1
      type: int
    - variable: secret
      label: Secret
      type: password
      required: true
    - variable: open_registration
      label: 'Open Registration'
      default: true
      type: enum
      options:
        - true
        - false
    - variable: drone_admin
      label: 'Drone Admin'
      type: string
      required: false
    - variable: organizations
      label: Organizations
      type: string
      required: false
    - variable: remote_driver
      type: enum
      required: true
      label: 'Remote Driver'
      default: GitHub
      options:
        - GitHub
        - GitLab
        - Gogs
        - Bitbucket Cloud
        - Bitbucket Server
    - variable: remote_driver_client
      label: 'Remote Driver Client'
      description: 'Required for GitHub, Bitbucket Cloud, Bitbucket Server and GitLab'
      type: string
      required: false
    - variable: remote_driver_secret
      label: 'Remote Driver Secret'
      description: 'Required for GitHub, Bitbucket Cloud, Bitbucket Server and GitLab'
      type: multiline
      required: false
    - variable: remote_driver_url
      label: 'Remote Driver URL'
      description: 'Required for GitLab, Gogs and Bitbucket Server'
      type: string
      required: false
    - variable: remote_driver_user
      label: 'Remote Driver User'
      description: 'Required for BitBucket Server'
      type: string
      required: false
    - variable: remote_driver_password
      label: 'Remote Driver Password'
      description: 'Required for BitBucket Server'
      type: password
      required: false
    - variable: version
      label: Version
      type: enum
      default: 0.8.2
      options:
        - 0.8.5
        - 0.8.4
        - 0.8.2
        - 0.8.1
        - 0.8.0
        - 0.8
        - latest
    - variable: mysql_host
      label: 'Mysql Host'
      description: 'Leave empty to spin up a mysql docker container'
      type: string
      default: drone
      required: false
    - variable: mysql_user
      label: 'Mysql User'
      type: string
      default: drone
      required: true
    - variable: mysql_password
      label: 'Mysql Password'
      type: password
      required: true
    - variable: mysql_database
      label: 'Mysql Database'
      type: string
      default: drone
      required: true
    - variable: volume_driver
      label: 'Volume Driver'
      required: true
      default: rancher-nfs
      type: enum
      options:
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
        - local
    - variable: public_port
      label: 'Public Port'
      description: 'Leave empty if you do not want an exposed port'
      type: string
      required: false

services:
  agent:
    scale: ${agent_scale}
    start_on_create: true

  server:
    scale: 1
    start_on_create: true
    health_check:
      drain_timeout_ms: 10000
      healthy_threshold: 2
      interval: 2000
      port: 8000
      request_line: GET / HTTP/1.0
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3
