version: '2'

services:
  isso:
    image: sheogorath/isso-docker:0.10.6
{{- if (.Values.public_port)}}
    ports:
      - ${public_port}:80
{{- end}}
    environment:
      - ISSO_HOST=${host}
      - ISSO_NAME=${name}
      - ISSO_MAX_AGE=${max_age}
      - ISSO_REPLY_TO_SELF=${reply_to_self}
      - ISSO_REQUIRE_EMAIL=${require_email}
      - ISSO_REQUIRE_AUTHOR=${require_author}
    volume_driver: ${volume_driver}
    volumes:
      - {{.Stack.Name}}--isso-data:/data
