version: '2'

catalog:
  name: isso
  version: 0.1.0
  description: |
    A commenting server
  minimum_rancher_version: v1.5.5
  questions:
    - variable: volume_driver
      label: 'Volume Driver'
      type: enum
      required: true
      default: rancher-nfs
      options:
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
        - local
    - variable: host
      label: Host
      type: string
      required: true
    - variable: name
      label: Name
      type: string
      default: Comments
      required: true
    - variable: max_age
      label: 'Max Age'
      type: string
      default: 30m
      required: true
    - variable: reply_to_self
      label: 'Reply to Self'
      type: enum
      default: false
      options:
        - true
        - false
    - variable: require_email
      label: 'Require Email'
      type: enum
      default: false
      options:
        - true
        - false
    - variable: require_author
      label: 'Require Author'
      type: enum
      default: false
      options:
        - true
        - false
    - variable: public_port
      label: 'Public Port'
      description: 'Leave empty if you do not want an exposed port'
      type: string
      required: false

services:
  isso:
    scale: 1
    health_check:
      drain_timeout_ms: 10000
      healthy_threshold: 2
      interval: 2000
      port: 80
      request_line: GET / HTTP/1.0
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3
